language: ruby
rvm:
  - 1.9.3
env:
  global:
  - secure: AYvY68wW/6Q+Rr4+bHiSbfQNG/mjDdnZ6fvwzN9kxowEJ+7HGEPICE340Jncp6MhpvHjW6S/xWvfK4gf0VUsnDJFZhqHu2d9hlMK55apT1wUMWR0KsTFpIsyGaDLDsZh51RYG1gvVFwAEYFbA/UUSKwSLt2G1bCM2xBkhson218=
  - secure: gGYOBn3wYWFmh/Dp6zsZR8/PPdwPtt0bXjdwTG9y8KVFE5ffBOwauqdpHjQAhvlPc6vwXQqCSI7qCpJe7lxZCTcdcYA87DjpTsp7tPiZcSr6FWgmD1UIFOYiRSQvvPfJdEwpp5L+7ae9LIskJulN/XHVzLW5UXiudAKXmCnswdM=
after_success:
  - "curl --ftp-create-dirs -T '{index.html,404.html,favicon.ico}' -u $FTP_USER:$FTP_PASSWORD ftp://direct.deepumohan.com/public_html/deepumohan.com/"
  - "curl --ftp-create-dirs -T '{css/style.css}' -u $FTP_USER:$FTP_PASSWORD ftp://direct.deepumohan.com/public_html/deepumohan.com/css/"
  - "curl --ftp-create-dirs -T '{privacy-policy/index.html}' -u $FTP_USER:$FTP_PASSWORD ftp://direct.deepumohan.com/public_html/deepumohan.com/privacy-policy/"
