name: Publish to S3

# This workflow is triggered on pushes to the repository.
on:
  push:

jobs:
  deploy:
    name: Build and upload to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: npm install

    - run: npm run-script build

    - run: ls
