on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npm run-script build

      - name: upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy-staging:
    if: github.ref != 'refs/heads/main'
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: download dist
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          role-duration-seconds: 1200
          role-session-name: GitHubAction

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://staging.deepumohan.com/

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: download dist
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PRODUCTION }}
          role-duration-seconds: 1200
          role-session-name: GitHubAction

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://deepumohan.com/
